apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: client 
spec:
  selector:
    matchLabels:
      env: dev 
  replicas: 3
  template: 
    metadata: 
      name: my-pod 
      labels: 
        env: dev 
    spec: 
      containers: 
      - name: my-pod 
        image: raghav1674/angular-dev-logger:v1 
        resources:  
          requests: 
            cpu: "0.25"
            memory: "300Mi"
          limits: 
            cpu: "0.3"
            memory: "500Mi"
        ports: 
        - containerPort: 80 
