apiVersion: v1 
kind: Pod 
metadata:
  name: storage-1 
spec:
  containers:
  - name: mysql
    image: mysql:5
    resources:
      requests:
        cpu: "0.3"
        memory: "200Mi"
      limits: 
        cpu: "0.4"
        memory: "500Mi"
    volumeMounts:
      - mountPath: /var/lib/mysql
        name: mysql-volume
    env: 
    - name: MYSQL_ROOT_PASSWORD 
      value: redhat

  volumes:
  - name: mysql-volume 
    hostPath: 
      path: /tmp/mysql 
