apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-eks-cluster
  region: us-east-1

nodeGroups:
  - name: my-ng-1
    instanceType: t2.micro
    desiredCapacity: 1
    ssh:
      publicKeyName: eks-key-pair 
