apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: nginxsa-role 
  namespace: default
rules:
- apiGroups: 
    - ""
    - apps 
  resources:
  - pods 
  - deployments 
  - services
  - replicasets
  verbs:
  - "get"
  - "list"
  - "create"
  - "update"
  - "patch"
  - "delete"

    