apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginxsa-rb 
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role 
  name: nginxsa-role 
subjects: 
  - namespace: default
    kind: ServiceAccount
    name: nginxsa