---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: my-deployment
  labels:
    env: dev
spec: 
  strategy:
    rollingUpdate:
      maxSurge: 1 
      maxUnavailable: 0
  selector:
    matchLabels:
      env: dev 
  replicas: 2 
  template: 
    metadata:
      name: my-pod 
      labels: 
        env: dev
    spec: 
      containers:
      - name: my-con 
        image: httpd 
        ports: 
        - containerPort: 80
        resources: 
          requests: 
            cpu: "0.25"
            memory: "100Mi"
          limits: 
            cpu: "0.5"
            memory: "190Mi"
...
