apiVersion: v1 
kind: Pod 
metadata: 
  name: my-pod 
  labels: 
    env: dev 
spec: 
  containers: 
  - name: my-con 
    image: centos 
    command:
    - /bin/bash 
    - -c  
    args:
    - while true;do echo "Bye, world";done 
    ports: 
    - containerPort: 80  
    resources: 
      requests:
        cpu: "1" 
        memory: 100Mi
      limits: 
        cpu: "1"
        memory: 200Mi
    
