apiVersion: v1 
kind: Service 
metadata:
  name: pod-service 
  labels: 
    env: dev 
spec: 
  type: NodePort 
  ports: 
  - targetPort: 80 
    port: 81
    nodePort: 30000
  selector:
    env: dev 
    
